apps/models/others.py
__author__ = 'Afief'

from datetime import datetime

from peewee import CharField, TextField, BooleanField, ForeignKeyField, \
    DateField

from apps.models import db
from apps.models.auth import User


class Phile(db.Model):
    filename = CharField(max_length=100)
    filetype = CharField(max_length=100)
    filepath = TextField()


class Post(db.Model):
    judul = CharField(max_length=100)
    konten = TextField()
    date_created = DateField(default=datetime.now)
    publik = BooleanField(default=True)
    author = ForeignKeyField(User)

    class Meta:
        order_by = ('-date_created',)


class MataKuliah(db.Model):
    kode = CharField(max_length=5)
    judul = CharField(max_length=100)
    dosen = ForeignKeyField(User)

    class Meta:
        order_by = ('kode',)


class Tugas(db.Model):
    judul = CharField(max_length=100)
    keterangan = TextField(null=True)
    mata_kuliah = ForeignKeyField(MataKuliah)
    tanggal_dibuat = DateField(default=datetime.now)
    tanggal_terakhir = DateField()

    class Meta:
        order_by = ('-id',)


class TugasFile(db.Model):
    tugas = ForeignKeyField(Tugas)
    phile = ForeignKeyField(Phile)


class KumpulTugas(db.Model):
    tugas = ForeignKeyField(Tugas)
    mahasiswa = ForeignKeyField(User)
    tanggal_mengumpulkan = DateField(default=datetime.now)
    phile = ForeignKeyField(Phile)

    class Meta:
        order_by = ('-tanggal_mengumpulkan',)

apps/views/mhs/__init__.py
import os

from flask import render_template, request, url_for, current_app, \
    redirect, g
from peewee import JOIN
from werkzeug.datastructures import FileStorage

from werkzeug.utils import secure_filename

from apps.forms.others import KumpulkanTugasForm
from apps.models import User, Tugas, KumpulTugas, MataKuliah, Post, Level, \
    Phile, Profile, TugasFile
from apps.decorators import mhs_required, current_user


def generate_path(user_id, tugas_id):
    app = current_app
    user = current_user()
    path = os.path.join(app.config['MEDIA_ROOT'], 'uploads', user_id, 'tugas',
                        tugas_id)
    if not os.path.exists(path):
        os.makedirs(path)
    return path


@mhs_required
def home():
    dosens = (User.select(User, MataKuliah)
              .join(MataKuliah)
              .join(Level, JOIN.LEFT_OUTER, on=(User.level == Level.id))
              .join(Tugas, JOIN.LEFT_OUTER,
                    on=(Tugas.mata_kuliah == MataKuliah.id))
              .join(Profile, on=(User.profile == Profile.id))
              .group_by(User)
              .where(Level.name == 'dosen')
              .order_by(Profile.nama.asc()))
    dosen_id = request.args.get('dosen_id', None)
    if dosen_id:
        dosen = dosens.filter(User.id == dosen_id).get()
    else:
        dosen = dosens.first()
        dosen_id = dosen.id
    posts = Post.select().order_by(Post.id.desc())
    user = g.user
    return render_template('mhs/home.html', dosen=dosen, dosens=dosens,
                           posts=posts, dosen_id=dosen_id)


@mhs_required
def tugas_detail(tugas_id):
    user = current_user()
    dosens = (User
              .select(User, MataKuliah.judul, Profile.nama)
              .join(MataKuliah, on=(MataKuliah.dosen == User.id))
              .join(Level, JOIN.LEFT_OUTER, on=(User.level == Level.id))
              .join(Profile, on=(User.profile == Profile.id))
              .group_by(User)
              .where(Level.name == 'dosen')
              .order_by(Profile.nama.asc()))
    tugas = Tugas.get(Tugas.id == tugas_id)
    dosen_id = tugas.mata_kuliah.dosen.id
    file_list = TugasFile.select().where(TugasFile.tugas == tugas)
    try:
        sudah_mengumpulkan = KumpulTugas.get(KumpulTugas.tugas == tugas,
                                             KumpulTugas.mahasiswa == user)
    except KumpulTugas.DoesNotExist:
        sudah_mengumpulkan = False
    form = KumpulkanTugasForm(request.form)
    form.action = url_for('mhs:tugas:kumpulkan', tugas_id=tugas.id)
    return render_template('mhs/detail.html', tugas=tugas, dosens=dosens,
                           form=form,
                           sudah_mengumpulkan=sudah_mengumpulkan,
                           dosen_id=dosen_id,
                           file_list=file_list)


@mhs_required
def tugas_kumpulkan(tugas_id):
    tugas = Tugas.get(Tugas.id == tugas_id)
    user = current_user()
    kumpul_tugas = KumpulTugas()
    kumpul_tugas.mahasiswa = user
    kumpul_tugas.tugas = tugas
    phile = request.files['phile']
    if isinstance(phile, FileStorage):
        path = generate_path(str(user.id), str(tugas.id))
        path = os.path.join(path, secure_filename(phile.filename))
        phile.save(path)
        f = Phile()
        f.filename = phile.filename
        f.filetype = phile.mimetype
        f.filepath = path
        f.save()
        kumpul_tugas.phile = f
    kumpul_tugas.save()
    return redirect(url_for('mhs:tugas:detail', tugas_id=tugas.id))

apps/templates/mhs/base.html
{% extends 'layout.html' %}
{% block body %}
    <div class="container-fluid">
        {% block content_heading %}
        {% endblock %}
        <div class="row">
            <div class="col-md-2">
                <div class="list-group">
                    {% for d in dosens %}
                        <a href="{{ url_for('mhs:home') }}?dosen_id={{ d.id }}"
                           class="list-group-item{% if (dosen_id|int) == d.id %} active{% endif %}">
                            {{ d.profile.nama }} - {{ d.matakuliah.judul }}
                        </a>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-10">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </div>
{% endblock body %}

apps/templates/mhs/detail.html
{% extends 'mhs/base.html' %}
{% from 'macro/home.html' import render_form %}

{% block head_tail %}
    <style>
        .mhs-tugas-detail {
            background: #f8f8f8;
            padding: 10px 20px;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-9 mhs-tugas-detail">
            <div class="row">
                <div class="col-md-9">
                    <h4 class="tugas-title">{{ tugas.judul }}</h4>

                    <div class="tugas-meta">
                        <small><i
                                class="glyphicon glyphicon-calendar"> {{ tugas.tanggal_terakhir }}</i>
                        </small>
                        <small><i
                                class="glyphicon glyphicon-book"> {{ tugas.mata_kuliah.judul }}</i>
                        </small>
                    </div>
                    <div class="tugas-keterangan">
                        {{ tugas.keterangan|safe|default('Tidak ada keterangan') }}
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="panel panel-default">
                        <div class="panel-heading">File pendukung</div>
                        <div class="panel-body">
                            <ul>
                                {% for file in tugas.tugasfile_set %}
                                    <li>
                                        <a href="{{ url_for('sendfile', file_id=file.phile.id, download=True) }}">{{ file.phile.filename }}</a>
                                    </li>
                                {% else %}
                                    Tidak ada file pedukung yang di upload.
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            {% if sudah_mengumpulkan %}
                <div class="panel panel-success">
                    <div class="panel-heading">Kumpulkan Tugas</div>
                    <div class="panel-body"><i
                            class="glyphicon glyphicon-ok"></i> Selesai
                    </div>
                </div>
            {% else %}
                <div class="panel panel-default">
                    <div class="panel-heading">Kumpulkan Tugas</div>
                    <div class="panel-body">
                        <form action="{{ url_for('mhs:tugas:kumpulkan', tugas_id=tugas.id) }}"
                              method="post"
                              enctype="multipart/form-data">
                            <div class="form-group">
                                <label for="phile">File Tugas</label>
                                <input type="file" class="form-control"
                                       id="phile" name="phile">
                            </div>
                            <input type="submit" value="Submit"
                                   class="btn btn-primary">
                        </form>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>

{% endblock %}

apps/templates/mhs/home.html
{% extends 'mhs/base.html' %}
{% block head_tail %}
    <style>
        body {
            background: url("{{ url_for('static', filename='img/noise2.png') }}");
        }

        h4.berita, h4.info-mahasiswa {
            color: #f8f8f8;
        }

        .list-group-berita {
            overflow: auto;
            max-height: 200px;
        }

        .list-group-berita .list-group-item:first-child {
            border-top-right-radius: 0;
        }

        .list-group-berita .list-group-item:last-child {
            border-bottom-right-radius: 0;
        }

        .td-label {
            font-weight: bold;
        }

        .panel-info {
            padding: 1rem;
        }

        .btn-update-info {
            margin-top: 5px;
        }
    </style>
{% endblock %}
{% block content_heading %}
    <div class="row">
        <div class="col-md-9">
            <h4 class="berita">Berita Terbaru</h4>

            <div class="list-group list-group-berita">
                {% for post in posts %}
                    <a href="{{ url_for('post:detail', post_id=post.id) }}"
                       class="list-group-item">
                        <h4 class="list-group-item-heading">{{ post.judul }}</h4>

                        <p class="list-group-item-text">{{ post.konten|striptags|truncate(150) }}</p>
                    </a>
                {% else %}
                    <a href="#" class="list-group-item">
                        <div class="list-group-item-heading">Tidak ada berita
                        </div>
                        <div class="list-group-item-text">Kosong</div>
                    </a>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-3">
            <h4 class="info-mahasiswa">
                Informasi Mahasiswa
            </h4>

            <div class="panel panel-default panel-info">
                <div class="row">
                    <div class="col-md-4">
                        <img class="img-thumbnail prof-pict"
                             src="{{ g.user.profile.image|default
                             ('/static/img/default-account.jpg') }}"
                             title="{{ g.user.profile.nama|default('Profil') }}">
                    </div>
                    <div class="col-md-8">
                        <table>
                            <tr>
                                <td class="td-label">
                                    Nama
                                </td>
                                <td class="td-label">:</td>
                                <td>{{ g.user.profile.nama }}</td>
                            </tr>
                            <tr>
                                <td class="td-label">No. Induk</td>
                                <td class="td-label">:</td>
                                <td>{{ g.user.no_induk }}</td>
                            </tr>
                            <tr>
                                <td class="td-label">Email</td>
                                <td class="td-label">:</td>
                                <td>{{ g.user.email }}</td>
                            </tr>
                            <tr>
                                <td class="td-label">No. Telpon</td>
                                <td class="td-label">:</td>
                                <td>{{ g.user.profile.no_telpon }}</td>
                            </tr>
                            <tr>
                                <td class="td-label">Tgl. Lahir</td>
                                <td class="td-label">:</td>
                                <td>{{ g.user.profile.tanggal_lahir }}</td>
                            </tr>
                            <tr>
                                <td class="td-label">Alamat</td>
                                <td class="td-label">:</td>
                                <td>{{ g.user.profile.alamat }}</td>
                            </tr>
                        </table>
                        <a href="{{ url_for('update-info', user_id=g.user.id) }}"
                           class="btn btn-default btn-xs btn-update-info">Update
                            Informasi</a>
                        <a href="{{ url_for('change-password', user_id=g.user.id) }}"
                           class="btn btn-danger btn-xs btn-update-info">Ganti
                            Password</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block content %}
    <div class="list-group tugas">
        {% for tugas in dosen.matakuliah.tugas_set %}
            <a href="{{ url_for('mhs:tugas:detail', tugas_id=tugas.id) }}"
               class="list-group-item">
                <h4 class="list-group-item-heading">{{ tugas.judul }}</h4>

                <p class="list-group-item-text">
                    <i class="glyphicon glyphicon-calendar"></i> {{ tugas.tanggal_terakhir }}
                    |
                    <i class="glyphicon glyphicon-info-sign"></i> {{ tugas.keterangan|striptags|truncate(150)|default('Tidak ada keterangan') }}
                </p>
            </a>
        {% else %}
            <p class="list-group-item">Tidak ada tugas untuk mata
                kuliah {{ dosen.matakuliah.judul }}</p>
        {% endfor %}
    </div>
{% endblock %}