apps/models/others.py
__author__ = 'Afief'

from datetime import datetime

from peewee import CharField, TextField, BooleanField, ForeignKeyField, \
    DateField

from apps.models import db
from apps.models.auth import User


class Phile(db.Model):
    filename = CharField(max_length=100)
    filetype = CharField(max_length=100)
    filepath = TextField()


class Post(db.Model):
    judul = CharField(max_length=100)
    konten = TextField()
    date_created = DateField(default=datetime.now)
    publik = BooleanField(default=True)
    author = ForeignKeyField(User)

    class Meta:
        order_by = ('-date_created',)


class MataKuliah(db.Model):
    kode = CharField(max_length=5)
    judul = CharField(max_length=100)
    dosen = ForeignKeyField(User)

    class Meta:
        order_by = ('kode',)


class Tugas(db.Model):
    judul = CharField(max_length=100)
    keterangan = TextField(null=True)
    mata_kuliah = ForeignKeyField(MataKuliah)
    tanggal_dibuat = DateField(default=datetime.now)
    tanggal_terakhir = DateField()

    class Meta:
        order_by = ('-id',)


class TugasFile(db.Model):
    tugas = ForeignKeyField(Tugas)
    phile = ForeignKeyField(Phile)


class KumpulTugas(db.Model):
    tugas = ForeignKeyField(Tugas)
    mahasiswa = ForeignKeyField(User)
    tanggal_mengumpulkan = DateField(default=datetime.now)
    phile = ForeignKeyField(Phile)

    class Meta:
        order_by = ('-tanggal_mengumpulkan',)

apps/views/dosen/__init__.py
from flask import render_template, g, flash, redirect, url_for, request
from flask_peewee.utils import object_list
from werkzeug.datastructures import FileStorage
from werkzeug.utils import secure_filename
from peewee import fn, JOIN

from apps.forms.others import TugasForm
from apps.models import KumpulTugas, Tugas, MataKuliah, TugasFile, Phile
from apps.decorators import dosen_required, current_user
from apps.views import generate_path


@dosen_required
def home():
    return redirect(url_for('dosen:tugas:list'))


@dosen_required
def tugas_list():
    tugass = (
    Tugas.select(Tugas, fn.Count(KumpulTugas.id).alias('k_tugas_count'))
    .join(KumpulTugas, JOIN.LEFT_OUTER, on=(KumpulTugas.tugas == Tugas.id))
    .join(MataKuliah, on=(Tugas.mata_kuliah == MataKuliah.id))
    .group_by(Tugas)
    .where(MataKuliah.dosen == current_user()))

    return object_list('dosen/tugas/list.html', tugass, var_name='tugass',
                       paginate_by=10)


@dosen_required
def tugas_delete(tugas_id):
    if g.user and g.user.level.name == 'dosen':
        tugas = None
        try:
            tugas = Tugas.get(Tugas.id == tugas_id)
        except Tugas.DoesNotExist:
            flash('Tidak bisa menghapus tugas', 'error')
        if tugas:
            tugas.delete_instance(True)
            flash('Sukses menghapus tugas')
        return redirect(url_for('dosen:tugas:list'))
    return render_template('dosen/tugas/list.html')


@dosen_required
def tugas_update(tugas_id):
    tugas = Tugas.get(Tugas.id == tugas_id)
    user = g.user
    form = TugasForm(request.form, obj=tugas)
    form.action = url_for('dosen:tugas:update', tugas_id=tugas_id)
    matkul = MataKuliah.get(MataKuliah.dosen == user)
    if form.validate_on_submit():
        form.populate_obj(tugas)
        tugas.mata_kuliah = matkul
        tugas.save()
        flash('Sukses memperbarui tugas')
        return redirect(url_for('dosen:tugas:list'))
    return render_template('dosen/tugas/update.html', form=form)


@dosen_required
def tugas_create():
    form = TugasForm(request.form)
    if form.validate_on_submit():
        tugas = Tugas()
        form.populate_obj(tugas)
        user = g.user
        matkul = MataKuliah.get(MataKuliah.dosen == user)
        tugas.mata_kuliah = matkul
        tugas.save()

        file_list = request.files.getlist('file_pendukung')
        for f in file_list:
            if isinstance(f, FileStorage) and len(f.filename) != 0:
                import os
                path = generate_path()
                save_to = os.path.join(path, secure_filename(user.email))
                if not os.path.exists(save_to):
                    os.makedirs(save_to)
                tujuan = os.path.join(save_to, secure_filename(f.filename))
                f.save(tujuan)
                p = Phile.create(
                    filename=f.filename,
                    filepath=tujuan,
                    filetype=f.mimetype
                )
                TugasFile.create(tugas=tugas, phile=p)
        flash('Sukses membuat tugas')
        return redirect(url_for('dosen:tugas:list'))
    return render_template('dosen/tugas/create.html', form=form)


@dosen_required
def tugas_detail(tugas_id):
    tugas = (Tugas.select(Tugas, KumpulTugas)
             .join(KumpulTugas, JOIN.LEFT_OUTER,
                   on=(KumpulTugas.tugas == Tugas.id))
             .where(Tugas.id == tugas_id)).get()
    return render_template('dosen/tugas/detail.html', tugas=tugas)

apps/templates/dosen/tugas/create.html
{% extends 'dosen/home.html' %}
{% from 'macro/home.html' import render_field %}
{% block content %}
    <div class="admin-content-header">
        <a href="{{ url_for('dosen:tugas:list') }}" class="btn btn-default">Kembali</a>
    </div>
    <form action="{{ form.action }}" class="form-horizontal" method="post"
          enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        {{ render_field(form.judul) }}
        {{ render_field(form.keterangan) }}
        {{ render_field(form.tanggal_terakhir) }}
        <div class="form-group">
            {{ form.file_pendukung.label(class_='col-md-2 control-label', multiple=True) }}
            <div class="col-md-10">
                {% if form.file_pendukung.errors %}
                    {{ form.file_pendukung(class_='form-control validation-error', title=field.description, placeholder=field.label.text, multiple=True) }}
                    {% for error in form.file_pendukung.errors %}
                        <small class="validation-error-message">{{ error }}</small>
                    {% endfor %}
                {% else %}
                    {{ form.file_pendukung(class='form-control', multiple=True) }}
                {% endif %}
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                <input type="submit" class="btn btn-primary">
            </div>
        </div>
    </form>
{% endblock %}

apps/templates/dosen/tugas/detail.html
{% extends 'dosen/home.html' %}

{% block content %}
    <div class="admin-content-header">
        <a href="{{ url_for('dosen:tugas:list') }}" class="btn btn-default">Kembali</a>
    </div>
    <div class="row">
        <div class="col-md-10">
            <h4 class="tugas-title">{{ tugas.judul }}</h4>

            <div class="tugas-meta">
                <small><i
                        class="glyphicon glyphicon-calendar"></i> {{ tugas.tanggal_terakhir }}
                </small>
                <small><i
                        class="glyphicon glyphicon-book"></i> {{ tugas.mata_kuliah.judul }}
                </small>
            </div>
            <div class="tugas-keterangan">
                {{ tugas.keterangan|safe }}
            </div>
        </div>
        <div class="col-md-2">
            <div class="panel panel-default">
                <div class="panel-heading">Mahasiswa yang sudah mengumpulkan
                </div>
                <div class="panel-body">
                    <ul>
                        {% for data in tugas.kumpultugas_set %}
                            <li>{{ data.mahasiswa.profile.nama }} - <a
                                    href="{{ url_for('sendfile', file_id=data.phile.id, download=True) }}">download</a>
                            </li>
                        {% else %}
                            Tidak ada yang mengumpulkan
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

apps/templates/dosen/tugas/list.html
{% extends 'dosen/home.html' %}

{% block content %}
    <div class="admin-content-header">
        <a href="{{ url_for('dosen:tugas:create') }}" class="btn btn-info">Buat
            Tugas Baru</a>
    </div>
    <table class="table table-bordered table-striped">
        <tr>
            <th width="3%">No.</th>
            <th>Judul</th>
            <th width="15%">Mata Kuliah</th>
            <th width="15%">Tanggal Terakhir</th>
            <th width="15%">Total Mengumpulkan</th>
            <th width="10%">Aksi</th>
        </tr>
        {% for tugas in tugass %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>
                    <a href="{{ url_for('dosen:tugas:detail', tugas_id=tugas.id) }}">{{ tugas.judul }}</a>
                </td>
                <td>{{ tugas.mata_kuliah.judul }}</td>
                <td>{{ tugas.tanggal_terakhir|datetime }}</td>
                <td>{{ tugas.k_tugas_count|default('0') }} Mahasiswa</td>
                <td>
                    <div class="btn-group btn-group-xs">
                        <a href="{{ url_for('dosen:tugas:update', tugas_id=tugas.id) }}"
                           class="btn btn-default">Update</a>
                        <a href="{{ url_for('dosen:tugas:delete', tugas_id=tugas.id) }}"
                           onclick="delete_this('{{ url_for('dosen:tugas:delete', tugas_id=tugas.id) }}')"
                           class="btn btn-danger">Delete</a>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">Tabel Tugas kosong</td>
            </tr>
        {% endfor %}
    </table>
    <nav>
        <ul class="pager">
            {% if page > 1 %}
                <li><a href="?page={{ page - 1 }}">Previous</a></li>
            {% else %}
                <li class="disabled"><a href="#">Previous</a></li>
            {% endif %}
            {% if page < pagination.get_pages() %}
                <li><a href="?page={{ page + 1 }}">Next</a></li>
            {% else %}
                <li class="disabled"><a href="#">Next</a></li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

apps/templates/dosen/tugas/update.html
{% extends 'dosen/home.html' %}
{% from 'macro/home.html' import render_form %}

{% block content %}
    <div class="admin-content-header">
        <a href="{{ url_for('dosen:tugas:list') }}" class="btn btn-default">Kembali</a>
    </div>
    {{ render_form(form) }}
{% endblock %}